- name: My playbook with Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Check if Docker is installed
      stat:
        path: /usr/bin/docker
      register: docker_installed

    - name: Install docker.io & python3-docker if not already installed
      apt:
        name: docker.io,python3-docker
        state: present
        cache_valid_time: 3600
      when: docker_installed.stat.exists == False

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Docker Compose is installed
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system|lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      when: ansible_system is defined and ansible_architecture is defined

    - name: Ensure rsync is installed
      apt:
        name: rsync
        state: present

    - name: Remove existing application directory
      file:
        path: /tmp/build
        state: absent
      ignore_errors: yes

    - name: Recreate application directory
      file:
        path: /tmp/build
        state: directory

    - name: Synchronize application files
      synchronize:
        src: /home/vagrant/devopsfinal/
        dest: /tmp/build
        delete: yes
        checksum: yes
        rsync_opts:
          - "--delete"

    - name: Ensure docker-compose.yaml is present
      copy:
        src: /home/vagrant/devopsfinal/docker-compose.yaml
        dest: /tmp/build/docker-compose.yaml

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /tmp/build
      register: result
      ignore_errors: yes

    - name: Print result of docker-compose up
      debug:
        var: result